### ISSUE TITLE
Setting up Automated testing (Backend)

### ISSUE THREAD

**Issue by amos1969** [boolean-uk/team-dev-client-ex-2410-team3#25]
# Automated Test

## Overview

The aim of implementing automated tests is to increase validity and reliability of the code.
The tests will be implemented in [Jasmine](https://jasmine.github.io/), a testing framework for JavaScript compatible with Node and Prisma, with [Github Actions](https://github.com/features/actions) to enable automation. This means that the pipeline will run Jasmine whenever there is a push  request to the ``main`` branch.

### Tests and Dependencies

- Firstly, Jasmine needs to be installed and initialized:
``npm install --save-dev jasmine``
 ``npx jasmine init``
- Secondly, the ``package.json`` needs to be updated to run the tests:
```
"scripts": {
  "test": "jasmine"
}
```
- Thirdly, tests need to be written.

### Creating github action workflow

- Creatin a new file : ``.github/workflows/test.yml``
- Adding the YAML configuration in this file to set up a pipeline.
- Push the workflow to Github. Github actions will then automatically run the Jasmine tests on each push or pull request to ``main``
- The results of these tests should be able to be viewed under the **Actions** tab. Any test failures will cause the pipeline to fail.

## Further Practical Implementation

The ``.github/workflows/test.yml`` will likely be implemented like, or similar to, this:
```
name: Run Jasmine Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jasmine tests
        run: npm test
```
